rails_tutorial: "http://www.railstutorial.org/"
rails_tutorial_book: "http://www.railstutorial.org/book"
rails_tutorial_contact: "http://www.railstutorial.org/contact"
rails_tutorial_help: "http://www.railstutorial.org/help"
screencast_series: "http://screencasts.railstutorial.org/"
rails_homepage: "http://rubyonrails.org/"
